# 1. Librerias

In [1]:
import cv2
print("OpenCV version:", cv2.__version__)

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

import sklearn 
print("Sklearn version:", sklearn.__version__)

import skimage
print("Skimage version:", skimage.__version__)

import numpy as np
print("Numpy version:", np.__version__)

import pandas as pd
print("Pandas version:", pd.__version__)

OpenCV version: 3.4.2


2022-06-07 21:24:53.420162: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-06-07 21:24:53.420224: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


TensorFlow version: 2.3.1
Sklearn version: 1.0.2
Skimage version: 0.19.2
Numpy version: 1.18.5
Pandas version: 1.3.5


# 2. Procesamiento de Imagenes

### Cargando Imagenes

In [2]:
img = cv2.imread("../images/pruebas/banana-ejemplo.jpg") # importamos la foto en matriz de RGB
img

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [3]:
cv2.imshow("test", img) # Siempre necesita dos argumentos, el nombre de la ventana que se va a abrir y la imgen pasada por cv2.imread()
cv2.waitKey(0) # Tecla 0 para parar la ejecucion de la celda tras hacer click en la ventana de la foto
# cv2.destroyAllWindows() # Cierra todas las ventas

48

## Tipos de imagenes

![Tipo de Imagenes](imagenes_apuntes/tipos_imagenes.jpg)

### RGB to HSV

In [4]:
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV) # Pasamos la imagen de RGB HSV. Estamos midiendo ahora: el tono, la saturacion y la intensidad
# Las valores ya no representan el Rojo Verde y Azul
hsv # Todo lo blanco me lo pone como 0

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       ...,

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255]]

### Intensidad (Escala de Grises)

In [5]:
# Intensidad = (R+G+B) / 3
# Podemos medir la intensidad al promediarlos. Pasamos el RGB a un solo valor que entara entre 0 y 255
img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) # Pasamos la imgaen a blanco y negro en scala de grises
img_gray

48

In [ ]:
# Sacamos la imagen por pantalla
# cv2.imshow("test",img_gray)
# cv2.waitKey(0) # Tecla 0 para parar la ejecucion de la celda tras hacer click en la ventana de la foto

In [19]:
# cv2.destroyAllWindows() # Cierra todas las ventas

### Binario (Blanco o Negro) Resaltar objetos

In [17]:
umbral = 200 # Podemos definiendo que todo lo que este por debajo de 200 nos lo de como 255

binary = np.uint8(img_gray<200)*255 # si un valor es mejor que 200 me dara 1. lo multiplico por 255 para hacer una imagen de contraste en clave de dos valores lo que no me darra 0
binary

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [18]:
# Sacamos la imagen por pantalla
cv2.imshow("test",binary)
cv2.waitKey(0) # Tecla para cerrar la venta con el 0
# cv2.destroyAllWindows() # Cierra todas las ventas

48

## Operaciones con los elementos de las Imagenes

### Suma

Minimo

### Histograma

In [ ]:
# Como podemos hacer una herramienta que nos resalta toda la banana por encima del fondo blanco?
# Utilizando la herramienta de histograma